"use client";

import { Check, MapPin, Plus, Scissors, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import type { FinanceMutate, OpenTransactions } from "@/components/finance-ui-types";
import { isLocationIndependentCategory } from "@/lib/locations/attribution";
import type { WorkspaceData, WorkspaceLocationPeriod } from "@/lib/workspace/demo";

export function LocationsAndStays({ workspace, personId, mutate, openTransactions }: { workspace: WorkspaceData; personId?: string | null; mutate: FinanceMutate; openTransactions: OpenTransactions }) {
  const [showAdd, setShowAdd] = useState(false);
  const periods = workspace.locationPeriods;
  const confirmed = periods.filter((period) => period.status === "confirmed");
  const suggested = periods.filter((period) => period.status === "suggested");
  const idsFor = (period: WorkspaceLocationPeriod) => period.id.startsWith("suggested:") ? arrayEvidence(period.evidence.transactionIds) : workspace.transactions.filter((transaction) => {
    if (isLocationIndependentCategory(transaction.category?.name)) return false;
    if (transaction.location_period?.id === period.id) return true;
    if (!transaction.travel_date || transaction.travel_destination?.toUpperCase() !== period.location.country_code?.toUpperCase()) return false;
    return transaction.travel_date >= period.starts_on && transaction.travel_date <= (period.ends_on || workspace.asOfDate);
  }).map((transaction) => transaction.id);
  const saveGenerated = async (period: WorkspaceLocationPeriod, status: "confirmed" | "rejected") => mutate("/api/locations", "POST", { personId, countryName: period.location.country_name || period.location.name, countryCode: period.location.country_code, locationName: period.location.name, defaultCurrency: period.location.default_currency, startsOn: period.starts_on, endsOn: period.ends_on, status, periodType: period.period_type, confidence: period.confidence, explanation: period.explanation, evidence: period.evidence, transactionIds: idsFor(period) });

  return <section className="mt-7 space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Locations and stays</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[var(--muted)]">Suggestions require repeated evidence. Currency alone never changes your location, and no period is automatically described as a vacation.</p></div><button disabled={!personId} title={personId ? undefined : "Choose Luciana or Julian before adding a personal stay."} onClick={() => setShowAdd((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-[var(--forest)] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45"><Plus aria-hidden="true" className="size-4" />Add location period</button></div>
    {showAdd ? <ManualLocationForm personId={personId} mutate={mutate} onDone={() => setShowAdd(false)} /> : null}

    <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
      <article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Suggestions to review</h2><p className="mt-1 text-sm text-[var(--muted)]">Confirm, edit, or reject each proposed period.</p><div className="mt-4 space-y-3">{suggested.map((period) => <div key={period.id} className="rounded-2xl border border-[#e3bf9f] bg-[#fbefe4] p-4"><div className="flex items-start gap-3"><MapPin aria-hidden="true" className="mt-0.5 size-5 text-[var(--amber)]" /><div className="min-w-0 flex-1"><h3 className="font-semibold">Possible {period.location.country_name || period.location.name} stay</h3><p className="mt-1 text-xs font-medium">{period.starts_on} to {period.ends_on || "ongoing"} · {Math.round(period.confidence * 100)}% confidence</p><p className="mt-2 text-xs leading-5 text-[#74411f]">{period.explanation}</p><button onClick={() => openTransactions({ title: `Evidence for possible ${period.location.country_name || period.location.name} stay`, transactionIds: idsFor(period), range: { from: period.starts_on, to: period.ends_on || workspace.asOfDate } })} className="mt-2 text-xs font-semibold underline underline-offset-4">Open {idsFor(period).length} supporting transactions</button><div className="mt-4 flex flex-wrap gap-2"><button disabled={workspace.mode !== "live"} onClick={() => void saveGenerated(period, "confirmed")} className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--forest)] px-3 py-2 text-xs font-semibold text-white disabled:opacity-45"><Check aria-hidden="true" className="size-3.5" />Confirm</button><button disabled={workspace.mode !== "live"} onClick={() => void saveGenerated(period, "rejected")} className="inline-flex items-center gap-1.5 rounded-lg border border-[#d6b18f] px-3 py-2 text-xs font-semibold disabled:opacity-45"><X aria-hidden="true" className="size-3.5" />Reject</button></div></div></div></div>)}{!suggested.length ? <p className="rounded-xl bg-[var(--paper)] p-4 text-sm text-[var(--muted)]">No unreviewed location suggestions.</p> : null}</div></article>
      <article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Confirmed periods</h2><p className="mt-1 text-sm text-[var(--muted)]">Dates, type, and purpose remain editable.</p><div className="mt-4 space-y-3">{confirmed.map((period, index) => <ConfirmedPeriod key={period.id} period={period} next={confirmed[index + 1] ?? null} workspace={workspace} mutate={mutate} transactionIds={idsFor(period)} openTransactions={openTransactions} />)}{!confirmed.length ? <p className="rounded-xl bg-[var(--paper)] p-4 text-sm text-[var(--muted)]">Confirm a suggestion or add a location period manually.</p> : null}</div></article>
    </div>
  </section>;
}

function ConfirmedPeriod({ period, next, workspace, mutate, transactionIds, openTransactions }: { period: WorkspaceLocationPeriod; next: WorkspaceLocationPeriod | null; workspace: WorkspaceData; mutate: FinanceMutate; transactionIds: string[]; openTransactions: OpenTransactions }) {
  const [from, setFrom] = useState(period.starts_on);
  const [to, setTo] = useState(period.ends_on ?? "");
  const [splitOn, setSplitOn] = useState("");
  const range = useMemo(() => ({ from: period.starts_on, to: period.ends_on || workspace.asOfDate }), [period, workspace.asOfDate]);
  const related = workspace.transactions.filter((transaction) => transactionIds.includes(transaction.id) && transaction.status === "posted" && !transaction.excluded_from_totals && Number(transaction.amount) < 0 && ["expense", "fee", "tax"].includes(transaction.kind) && !isLocationIndependentCategory(transaction.category?.name));
  const spend = tripSpend(related);
  return <div className="rounded-2xl bg-[var(--paper)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{period.location.country_name || period.location.name}</h3><p className="mt-1 text-xs capitalize text-[var(--muted)]">{period.period_type.replaceAll("_", " ")}{period.trip_purpose ? ` · ${period.trip_purpose}` : ""}</p>{period.trip_purpose ? <><p className="mt-2 font-mono text-sm font-semibold text-[var(--forest)]">Trip spending: {spend.label}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{spend.count} spending transaction{spend.count === 1 ? "" : "s"}, including linked flights bought before the stay.</p></> : null}</div><button onClick={() => openTransactions({ title: `${period.location.country_name || period.location.name} transactions`, transactionIds, range })} className="text-xs font-semibold text-[var(--forest)]">{transactionIds.length} transactions</button></div><div className="mt-3 grid grid-cols-2 gap-2"><MiniDate label="From" value={from} onChange={setFrom} /><MiniDate label="To" value={to} onChange={setTo} /></div><div className="mt-3 flex flex-wrap gap-2"><button disabled={workspace.mode !== "live"} onClick={() => void mutate(`/api/locations/${period.id}`, "PATCH", { startsOn: from, endsOn: to || null })} className="rounded-lg border border-[var(--line)] px-3 py-1.5 text-xs font-semibold disabled:opacity-45">Save dates</button>{next && next.location.id === period.location.id ? <button disabled={workspace.mode !== "live"} onClick={() => void mutate(`/api/locations/${period.id}`, "PATCH", { action: "merge", targetPeriodId: next.id })} className="rounded-lg border border-[var(--line)] px-3 py-1.5 text-xs font-semibold disabled:opacity-45">Merge next</button> : null}</div><div className="mt-3 flex items-end gap-2 border-t border-[var(--line)] pt-3"><MiniDate label="Split on" value={splitOn} onChange={setSplitOn} /><button disabled={workspace.mode !== "live" || !splitOn} onClick={() => void mutate(`/api/locations/${period.id}`, "PATCH", { action: "split", splitOn })} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-[var(--line)] px-3 text-xs font-semibold disabled:opacity-45"><Scissors aria-hidden="true" className="size-3.5" />Split</button></div></div>;
}

function ManualLocationForm({ personId, mutate, onDone }: { personId?: string | null; mutate: FinanceMutate; onDone: () => void }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await mutate("/api/locations", "POST", { personId, countryName: data.get("countryName"), countryCode: data.get("countryCode") || null, locationName: data.get("locationName") || undefined, defaultCurrency: data.get("currency") || null, startsOn: data.get("startsOn"), endsOn: data.get("endsOn") || null, periodType: data.get("periodType"), tripPurpose: data.get("purpose") || null, status: "confirmed", confidence: 1, explanation: "Manually confirmed location period." }); onDone(); }; return <form onSubmit={(event) => void submit(event)} className="grid gap-3 rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-4 sm:grid-cols-4"><TextField label="Country" name="countryName" required /><TextField label="Country code" name="countryCode" placeholder="BR" /><TextField label="Location name" name="locationName" placeholder="São Paulo" /><TextField label="Local currency" name="currency" placeholder="BRL" /><TextField label="Start" name="startsOn" type="date" required /><TextField label="End" name="endsOn" type="date" /><label className="text-xs font-semibold">Period type<select name="periodType" className="field"><option value="stay">Stay</option><option value="temporary_stay">Temporary stay</option><option value="home_base">Home base</option><option value="location">Location</option></select></label><TextField label="Optional purpose" name="purpose" /><button className="h-10 self-end rounded-xl bg-[var(--forest)] px-4 text-sm font-semibold text-white">Save period</button></form>; }
function MiniDate({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-[10px] font-semibold text-[var(--muted)]">{label}<input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block h-9 w-full rounded-lg border border-[var(--line)] bg-white px-2 text-xs text-[var(--ink)]" /></label>; }
function TextField({ label, name, type = "text", required = false, placeholder }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string }) { return <label className="text-xs font-semibold">{label}<input name={name} type={type} required={required} placeholder={placeholder} className="field" /></label>; }
function arrayEvidence(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function tripSpend(transactions: WorkspaceData["transactions"]) {
  let usd = 0;
  let missing = 0;
  for (const transaction of transactions) {
    const direction = transaction.kind === "refund" ? -1 : 1;
    if (transaction.currency === "USD") usd += Math.abs(Number(transaction.amount)) * direction;
    else if (transaction.reporting_value?.reporting_currency === "USD") usd += Math.abs(Number(transaction.reporting_value.reporting_amount)) * direction;
    else missing += 1;
  }
  if (!transactions.length) return { label: "No spend found", count: 0 };
  const formatted = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(usd);
  return { label: `${formatted}${missing ? ` + ${missing} awaiting conversion` : ""}`, count: transactions.length };
}
