"use client";

import { Check, MapPin, Plus, Scissors, X } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import type { FinanceMutate, OpenTransactions } from "@/components/finance-ui-types";
import { buildTripExpenseReport, isTripPeriod, transactionIdsForLocationPeriod, type TripExpenseReport } from "@/lib/locations/trip-report";
import type { WorkspaceData, WorkspaceLocationPeriod } from "@/lib/workspace/demo";

export function LocationsAndStays({ workspace, personId, mutate, openTransactions }: { workspace: WorkspaceData; personId?: string | null; mutate: FinanceMutate; openTransactions: OpenTransactions }) {
  const [showAdd, setShowAdd] = useState(false);
  const periods = workspace.locationPeriods;
  const confirmed = periods.filter((period) => period.status === "confirmed");
  const suggested = periods.filter((period) => period.status === "suggested");
  const tripReports = useMemo(() => groupEquivalentTrips(confirmed.filter(isTripPeriod), Boolean(personId)).map((group) => buildTripExpenseReport(group[0], workspace.transactions, workspace.asOfDate, group.map((period) => period.id))).sort((left, right) => right.period.starts_on.localeCompare(left.period.starts_on)), [confirmed, personId, workspace.asOfDate, workspace.transactions]);
  const idsFor = (period: WorkspaceLocationPeriod) => period.id.startsWith("suggested:") ? arrayEvidence(period.evidence.transactionIds) : transactionIdsForLocationPeriod(period, workspace.transactions, workspace.asOfDate);
  const saveGenerated = async (period: WorkspaceLocationPeriod, status: "confirmed" | "rejected") => mutate("/api/locations", "POST", { personId, countryName: period.location.country_name || period.location.name, countryCode: period.location.country_code, locationName: period.location.name, defaultCurrency: period.location.default_currency, startsOn: period.starts_on, endsOn: period.ends_on, status, periodType: period.period_type, confidence: period.confidence, explanation: period.explanation, evidence: period.evidence, transactionIds: idsFor(period) });

  return <section className="mt-7 space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Locations and stays</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[var(--muted)]">Suggestions require repeated evidence. Currency alone never changes your location, and no period is automatically described as a vacation.</p></div><button disabled={!personId} title={personId ? undefined : "Choose Luciana or Julian before adding a personal stay."} onClick={() => setShowAdd((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-[var(--forest)] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45"><Plus aria-hidden="true" className="size-4" />Add location period</button></div>
    {showAdd ? <ManualLocationForm personId={personId} mutate={mutate} onDone={() => setShowAdd(false)} /> : null}

    <article className="rounded-[22px] border border-[var(--forest)] bg-[var(--surface)] p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[var(--forest)]">Travel overview</p><h2 className="mt-1 text-lg font-semibold">Trips and their spending</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[var(--muted)]">Each total uses the trip&apos;s real expenses and linked advance bookings. Subscriptions and Papaya Kids are excluded because they do not describe where you were.</p></div><span className="rounded-full bg-[var(--forest-soft)] px-3 py-1.5 text-xs font-semibold text-[var(--forest)]">USD · {tripReports.length} trip{tripReports.length === 1 ? "" : "s"}</span></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{tripReports.map((trip) => <TripExpenseCard key={trip.period.id} trip={trip} openTransactions={openTransactions} />)}{!tripReports.length ? <p className="rounded-2xl bg-[var(--paper)] p-5 text-sm text-[var(--muted)] lg:col-span-2">Confirmed temporary stays will appear here with their spending.</p> : null}</div>
    </article>

    <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]">
      <article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Suggestions to review</h2><p className="mt-1 text-sm text-[var(--muted)]">Confirm, edit, or reject each proposed period.</p><div className="mt-4 space-y-3">{suggested.map((period) => <div key={period.id} className="rounded-2xl border border-[#e3bf9f] bg-[#fbefe4] p-4"><div className="flex items-start gap-3"><MapPin aria-hidden="true" className="mt-0.5 size-5 text-[var(--amber)]" /><div className="min-w-0 flex-1"><h3 className="font-semibold">Possible {period.location.country_name || period.location.name} stay</h3><p className="mt-1 text-xs font-medium">{period.starts_on} to {period.ends_on || "ongoing"} · {Math.round(period.confidence * 100)}% confidence</p><p className="mt-2 text-xs leading-5 text-[#74411f]">{period.explanation}</p><button onClick={() => openTransactions({ title: `Evidence for possible ${period.location.country_name || period.location.name} stay`, transactionIds: idsFor(period), range: { from: period.starts_on, to: period.ends_on || workspace.asOfDate } })} className="mt-2 text-xs font-semibold underline underline-offset-4">Open {idsFor(period).length} supporting transactions</button><div className="mt-4 flex flex-wrap gap-2"><button disabled={workspace.mode !== "live"} onClick={() => void saveGenerated(period, "confirmed")} className="inline-flex items-center gap-1.5 rounded-lg bg-[var(--forest)] px-3 py-2 text-xs font-semibold text-white disabled:opacity-45"><Check aria-hidden="true" className="size-3.5" />Confirm</button><button disabled={workspace.mode !== "live"} onClick={() => void saveGenerated(period, "rejected")} className="inline-flex items-center gap-1.5 rounded-lg border border-[#d6b18f] px-3 py-2 text-xs font-semibold disabled:opacity-45"><X aria-hidden="true" className="size-3.5" />Reject</button></div></div></div></div>)}{!suggested.length ? <p className="rounded-xl bg-[var(--paper)] p-4 text-sm text-[var(--muted)]">No unreviewed location suggestions.</p> : null}</div></article>
      <article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Confirmed periods</h2><p className="mt-1 text-sm text-[var(--muted)]">Dates, type, and purpose remain editable.</p><div className="mt-4 space-y-3">{confirmed.map((period, index) => <ConfirmedPeriod key={period.id} period={period} next={confirmed[index + 1] ?? null} workspace={workspace} mutate={mutate} transactionIds={idsFor(period)} openTransactions={openTransactions} />)}{!confirmed.length ? <p className="rounded-xl bg-[var(--paper)] p-4 text-sm text-[var(--muted)]">Confirm a suggestion or add a location period manually.</p> : null}</div></article>
    </div>
  </section>;
}

function TripExpenseCard({ trip, openTransactions }: { trip: TripExpenseReport; openTransactions: OpenTransactions }) {
  const { period, report } = trip;
  const name = period.location.country_name || period.location.name;
  const maxCategory = Math.max(1, ...report.categories.map((category) => Math.abs(category.amount)));
  const currencies = report.originalCurrencies.map((item) => item.currency).join(", ") || "USD";
  return <section className="overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--paper)]">
    <div className="flex flex-wrap items-start justify-between gap-3 p-4 sm:p-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{name}</h3><span className="rounded-full bg-[#dceaf2] px-2 py-1 text-[9px] font-semibold uppercase tracking-[0.08em] text-[#315b73]">{period.trip_purpose || "Temporary stay"}</span></div><p className="mt-1 text-xs text-[var(--muted)]">{friendlyDate(period.starts_on)} – {friendlyDate(period.ends_on || "")}</p><p className="mt-1 text-[10px] text-[var(--muted)]">Original currencies: {currencies}</p></div><button type="button" onClick={() => openTransactions({ title: `${name} trip spending`, transactionIds: report.total.transactionIds, range: report.range })} className="rounded-xl bg-[var(--forest)] px-3 py-2 text-right text-white"><strong className="block font-mono text-base">{money(report.total.amount)}</strong><span className="block text-[9px] opacity-80">{report.total.transactionIds.length} expenses · open all</span></button></div>
    <div className="space-y-3 border-t border-[var(--line)] bg-white/60 p-4 sm:p-5">{report.categories.map((category) => <button key={category.id} type="button" onClick={() => openTransactions({ title: `${name} trip · ${category.name}`, transactionIds: category.transactionIds, range: report.range })} className="block w-full text-left"><div className="mb-1 flex items-center justify-between gap-3 text-xs"><span className="min-w-0 truncate"><span className="mr-2 inline-block size-2 rounded-full" style={{ backgroundColor: category.color }} />{category.name}</span><span className="shrink-0"><strong className="font-mono">{money(category.amount)}</strong><span className="ml-2 text-[9px] text-[var(--muted)]">{percentage(category.amount, report.total.amount)}</span></span></div><div className="h-1.5 overflow-hidden rounded-full bg-[var(--paper-deep)]"><div className="h-full rounded-full" style={{ width: `${Math.max(2, Math.abs(category.amount) / maxCategory * 100)}%`, backgroundColor: category.color }} /></div></button>)}{!report.categories.length ? <p className="text-xs text-[var(--muted)]">No spending transactions are linked to this trip yet.</p> : null}{report.missingFxTransactionIds.length ? <button type="button" onClick={() => openTransactions({ title: `${name} trip · awaiting USD conversion`, transactionIds: report.missingFxTransactionIds, range: report.range })} className="text-xs font-semibold text-[var(--amber)] underline underline-offset-4">{report.missingFxTransactionIds.length} transaction{report.missingFxTransactionIds.length === 1 ? " is" : "s are"} awaiting a USD conversion</button> : null}</div>
    <p className="border-t border-[var(--line)] px-4 py-3 text-[10px] leading-4 text-[var(--muted)]">Transaction window: {friendlyDate(report.range.from)} – {friendlyDate(report.range.to)}. This may begin before the stay when a flight or hotel was booked in advance.</p>
  </section>;
}

function ConfirmedPeriod({ period, next, workspace, mutate, transactionIds, openTransactions }: { period: WorkspaceLocationPeriod; next: WorkspaceLocationPeriod | null; workspace: WorkspaceData; mutate: FinanceMutate; transactionIds: string[]; openTransactions: OpenTransactions }) {
  const [from, setFrom] = useState(period.starts_on);
  const [to, setTo] = useState(period.ends_on ?? "");
  const [splitOn, setSplitOn] = useState("");
  const range = useMemo(() => ({ from: period.starts_on, to: period.ends_on || workspace.asOfDate }), [period, workspace.asOfDate]);
  return <div className="rounded-2xl bg-[var(--paper)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{period.location.country_name || period.location.name}</h3><p className="mt-1 text-xs capitalize text-[var(--muted)]">{period.period_type.replaceAll("_", " ")}{period.trip_purpose ? ` · ${period.trip_purpose}` : ""}</p></div><button onClick={() => openTransactions({ title: `${period.location.country_name || period.location.name} transactions`, transactionIds, range })} className="text-xs font-semibold text-[var(--forest)]">{transactionIds.length} transactions</button></div><div className="mt-3 grid grid-cols-2 gap-2"><MiniDate label="From" value={from} onChange={setFrom} /><MiniDate label="To" value={to} onChange={setTo} /></div><div className="mt-3 flex flex-wrap gap-2"><button disabled={workspace.mode !== "live"} onClick={() => void mutate(`/api/locations/${period.id}`, "PATCH", { startsOn: from, endsOn: to || null })} className="rounded-lg border border-[var(--line)] px-3 py-1.5 text-xs font-semibold disabled:opacity-45">Save dates</button>{next && next.location.id === period.location.id ? <button disabled={workspace.mode !== "live"} onClick={() => void mutate(`/api/locations/${period.id}`, "PATCH", { action: "merge", targetPeriodId: next.id })} className="rounded-lg border border-[var(--line)] px-3 py-1.5 text-xs font-semibold disabled:opacity-45">Merge next</button> : null}</div><div className="mt-3 flex items-end gap-2 border-t border-[var(--line)] pt-3"><MiniDate label="Split on" value={splitOn} onChange={setSplitOn} /><button disabled={workspace.mode !== "live" || !splitOn} onClick={() => void mutate(`/api/locations/${period.id}`, "PATCH", { action: "split", splitOn })} className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-[var(--line)] px-3 text-xs font-semibold disabled:opacity-45"><Scissors aria-hidden="true" className="size-3.5" />Split</button></div></div>;
}

function ManualLocationForm({ personId, mutate, onDone }: { personId?: string | null; mutate: FinanceMutate; onDone: () => void }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await mutate("/api/locations", "POST", { personId, countryName: data.get("countryName"), countryCode: data.get("countryCode") || null, locationName: data.get("locationName") || undefined, defaultCurrency: data.get("currency") || null, startsOn: data.get("startsOn"), endsOn: data.get("endsOn") || null, periodType: data.get("periodType"), tripPurpose: data.get("purpose") || null, status: "confirmed", confidence: 1, explanation: "Manually confirmed location period." }); onDone(); }; return <form onSubmit={(event) => void submit(event)} className="grid gap-3 rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-4 sm:grid-cols-4"><TextField label="Country" name="countryName" required /><TextField label="Country code" name="countryCode" placeholder="BR" /><TextField label="Location name" name="locationName" placeholder="São Paulo" /><TextField label="Local currency" name="currency" placeholder="BRL" /><TextField label="Start" name="startsOn" type="date" required /><TextField label="End" name="endsOn" type="date" /><label className="text-xs font-semibold">Period type<select name="periodType" className="field"><option value="stay">Stay</option><option value="temporary_stay">Temporary stay</option><option value="home_base">Home base</option><option value="location">Location</option></select></label><TextField label="Optional purpose" name="purpose" /><button className="h-10 self-end rounded-xl bg-[var(--forest)] px-4 text-sm font-semibold text-white">Save period</button></form>; }
function MiniDate({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-[10px] font-semibold text-[var(--muted)]">{label}<input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block h-9 w-full rounded-lg border border-[var(--line)] bg-white px-2 text-xs text-[var(--ink)]" /></label>; }
function TextField({ label, name, type = "text", required = false, placeholder }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string }) { return <label className="text-xs font-semibold">{label}<input name={name} type={type} required={required} placeholder={placeholder} className="field" /></label>; }
function arrayEvidence(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function groupEquivalentTrips(periods: WorkspaceLocationPeriod[], keepPeopleSeparate: boolean) {
  if (keepPeopleSeparate) return periods.map((period) => [period]);
  const groups = new Map<string, WorkspaceLocationPeriod[]>();
  for (const period of periods) {
    const key = [period.location.country_code || period.location.country_name || period.location.name, period.starts_on, period.ends_on || "ongoing"].join(":");
    groups.set(key, [...(groups.get(key) ?? []), period]);
  }
  return [...groups.values()];
}
function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value); }
function percentage(value: number, total: number) { return total ? `${Math.round(Math.abs(value) / Math.abs(total) * 100)}%` : "0%"; }
function friendlyDate(value: string) { return value ? new Date(`${value}T00:00:00Z`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }) : "Ongoing"; }
