"use client";

import { Check, CircleHelp, RefreshCw } from "lucide-react";
import { FormEvent } from "react";
import type { FinanceMutate, OpenTransactions } from "@/components/finance-ui-types";
import type { WorkspaceData, WorkspaceQuestion } from "@/lib/workspace/demo";

export function QuestionsInbox({ workspace, mutate, openTransactions }: { workspace: WorkspaceData; mutate: FinanceMutate; openTransactions: OpenTransactions }) {
  const live = workspace.mode === "live";
  const persistedKeys = new Set(workspace.questions.map((question) => question.group_key).filter(Boolean));
  const suggestions = workspace.suggestedQuestions.filter((question) => !persistedKeys.has(question.key));
  const refresh = async () => { try { await mutate("/api/intelligence/rebuild", "POST"); } catch (error) { window.alert(messageOf(error)); } };
  const resolve = async (id: string, body: Record<string, unknown>) => { try { await mutate(`/api/questions/${id}`, "PATCH", body); } catch (error) { window.alert(messageOf(error)); } };
  return <section className="mt-7 space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Proactive questions</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[var(--muted)]">Questions are grouped and ranked by their effect on spending. Each one includes the evidence used to ask it.</p></div><button disabled={!live} onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-2.5 text-sm font-semibold disabled:opacity-45"><RefreshCw aria-hidden="true" className="size-4" />Refresh questions</button></div>
    <div className="grid gap-4 xl:grid-cols-2">{workspace.questions.map((question) => <QuestionCard key={question.id} question={question} workspace={workspace} live={live} openTransactions={openTransactions} resolve={resolve} />)}{suggestions.map((question) => <article key={question.key} className="rounded-[20px] border border-[#e3bf9f] bg-[#fbefe4] p-5"><div className="flex items-start gap-3"><CircleHelp aria-hidden="true" className="mt-0.5 size-5 shrink-0 text-[var(--amber)]" /><div><span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#8a4b21]">Suggested · priority {question.priority}</span><h3 className="mt-1 font-semibold">{question.prompt}</h3><p className="mt-2 text-sm leading-6 text-[#74411f]">{question.explanation}</p><button onClick={() => openTransactions({ title: question.prompt, transactionIds: question.transactionIds, range: evidenceRange(workspace, question.transactionIds) })} className="mt-3 text-xs font-semibold underline underline-offset-4">Open {question.transactionIds.length} supporting transactions</button><p className="mt-3 text-xs text-[#74411f]">Refresh questions to save this grouped question before answering it.</p></div></div></article>)}{!workspace.questions.length && !suggestions.length ? <div className="xl:col-span-2"><Empty /></div> : null}</div>
  </section>;
}

function QuestionCard({ question, workspace, live, openTransactions, resolve }: { question: WorkspaceQuestion; workspace: WorkspaceData; live: boolean; openTransactions: OpenTransactions; resolve: (id: string, body: Record<string, unknown>) => Promise<void> }) {
  const ids = [...new Set([...(question.supporting_transaction_ids ?? []), ...(question.transaction_id ? [question.transaction_id] : [])])];
  const recurring = question.question_type.startsWith("recurring_") || question.question_type === "possible_multi_period_payment";
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await resolve(question.id, { status: "resolved", kind: "expense", excludedFromTotals: false, categoryId: data.get("categoryId") || null, personName: data.get("personName") || undefined, providerName: data.get("providerName") || undefined, frequency: data.get("frequency") || undefined, countryCode: data.get("countryCode") || undefined, note: data.get("note") || undefined, applyHistorical: true }); };
  return <article className="rounded-[20px] border border-[var(--line)] bg-[var(--surface)] p-5"><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[var(--amber-soft)] text-[var(--amber)]"><CircleHelp aria-hidden="true" className="size-4" /></span><div className="min-w-0 flex-1"><span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[var(--muted)]">Priority {question.priority ?? 50} · {question.question_type.replaceAll("_", " ")}</span><h3 className="mt-1 font-semibold">{question.prompt}</h3>{typeof question.context?.explanation === "string" ? <p className="mt-2 text-sm leading-6 text-[var(--muted)]">{question.context.explanation}</p> : null}<button onClick={() => openTransactions({ title: question.prompt, transactionIds: ids, range: evidenceRange(workspace, ids) })} className="mt-3 text-xs font-semibold text-[var(--forest)] underline underline-offset-4">Open {ids.length} supporting transaction{ids.length === 1 ? "" : "s"}</button>
      {recurring ? <form onSubmit={(event) => void submit(event)} className="mt-4 grid gap-2 sm:grid-cols-2"><SmallField label="Provider or person"><input name="providerName" className="field" placeholder="e.g. Jessy" /></SmallField><SmallField label="Known person"><input name="personName" className="field" placeholder="Optional" /></SmallField><SmallField label="Category"><select name="categoryId" className="field"><option value="">Choose category</option>{workspace.categories.map((category) => <option key={category.id} value={category.id}>{category.parent_id ? "↳ " : ""}{category.name}</option>)}</select></SmallField><SmallField label="Frequency"><select name="frequency" className="field"><option value="uncertain">Uncertain</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></select></SmallField><SmallField label="Country code"><input name="countryCode" className="field" placeholder="AR" /></SmallField><SmallField label="What this represents"><input name="note" className="field" placeholder="e.g. Psychology sessions" /></SmallField><button disabled={!live} className="rounded-xl bg-[var(--forest)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-45">Save and apply to history</button><button type="button" disabled={!live} onClick={() => void resolve(question.id, { status: "dismissed" })} className="rounded-xl px-4 py-2.5 text-sm text-[var(--muted)] disabled:opacity-45">Dismiss</button></form> : <div className="mt-4 flex flex-wrap gap-2"><Decision disabled={!live} label="Expense" onClick={() => void resolve(question.id, { status: "resolved", kind: "expense", excludedFromTotals: false })} /><Decision disabled={!live} label="Owned transfer" onClick={() => void resolve(question.id, { status: "resolved", kind: "transfer", excludedFromTotals: true })} /><Decision disabled={!live} label="Reimbursement" onClick={() => void resolve(question.id, { status: "resolved", kind: "refund", excludedFromTotals: false, note: "Reimbursement" })} /><Decision disabled={!live} label="Income" onClick={() => void resolve(question.id, { status: "resolved", kind: "income", excludedFromTotals: false })} /><button disabled={!live} onClick={() => void resolve(question.id, { status: "dismissed" })} className="rounded-xl px-3 py-2 text-sm text-[var(--muted)] disabled:opacity-45">Dismiss</button></div>}</div></div></article>;
}

function evidenceRange(workspace: WorkspaceData, ids: string[]) { const dates = workspace.transactions.filter((transaction) => ids.includes(transaction.id)).map((transaction) => transaction.occurred_at.slice(0,10)).sort(); return { from: dates[0] ?? `${workspace.asOfDate.slice(0,4)}-01-01`, to: dates.at(-1) ?? workspace.asOfDate }; }
function Decision({ label, onClick, disabled }: { label: string; onClick: () => void; disabled: boolean }) { return <button disabled={disabled} onClick={onClick} className="rounded-xl border border-[var(--line)] bg-[var(--paper)] px-3 py-2 text-sm font-semibold disabled:opacity-45">{label}</button>; }
function SmallField({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-semibold text-[var(--muted)]">{label}{children}</label>; }
function Empty() { return <div className="grid min-h-60 place-items-center rounded-[20px] border border-[var(--line)] bg-[var(--surface)] text-center"><div><Check aria-hidden="true" className="mx-auto size-6 text-[var(--forest)]" /><h2 className="mt-3 font-semibold">Inbox cleared</h2><p className="mt-1 text-sm text-[var(--muted)]">No evidence-backed question is waiting.</p></div></div>; }
function messageOf(error: unknown) { return error instanceof Error ? error.message : "The questions could not be refreshed."; }
