"use client";

import { CalendarClock, ChevronLeft, RefreshCw } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import type { FinanceMutate, OpenTransactions } from "@/components/finance-ui-types";
import { analyzeRecurring, type RecurringPattern } from "@/lib/intelligence/recurring";
import type { WorkspaceData, WorkspaceTransaction } from "@/lib/workspace/demo";

export function RecurringExpenses({ workspace, mutate, openTransactions }: { workspace: WorkspaceData; mutate: FinanceMutate; openTransactions: OpenTransactions }) {
  const analysis = useMemo(() => analyzeRecurring(workspace.transactions, workspace.asOfDate), [workspace.asOfDate, workspace.transactions]);
  const [selectedKey, setSelectedKey] = useState<string | null>(null);
  const selected = analysis.patterns.find((pattern) => pattern.key === selectedKey) ?? null;
  const persisted = selected ? workspace.recurringObligations.find((item) => item.merchant_key === selected.key) ?? null : null;
  const refresh = async () => { try { await mutate("/api/intelligence/rebuild", "POST"); } catch (error) { window.alert(messageOf(error)); } };
  if (selected) return <RecurringDetail pattern={selected} obligationId={persisted?.id ?? null} workspace={workspace} mutate={mutate} openTransactions={openTransactions} onBack={() => setSelectedKey(null)} />;

  const subscriptions = analysis.patterns.filter((pattern) => pattern.isSubscription);
  const sweatCandidates = workspace.transactions.filter((transaction) => transaction.status === "posted" && /\bapple\.com\/bill\b/i.test(transaction.description) && [9.99, 12.99].some((amount) => Math.abs(Math.abs(Number(transaction.amount)) - amount) < 0.001));
  const sweatRange = evidenceRange(sweatCandidates, workspace.asOfDate);
  return <section className="mt-7 space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Recurring expenses</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-[var(--muted)]">Cash payments and the service months they cover remain separate. Repeated providers become editable rules.</p></div><button disabled={workspace.mode !== "live"} onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-2.5 text-sm font-semibold disabled:opacity-45"><RefreshCw aria-hidden="true" className="size-4" />Refresh analysis</button></div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Known and possible obligations</h2><div className="mt-4 space-y-2">{analysis.patterns.map((pattern) => <button key={pattern.key} onClick={() => setSelectedKey(pattern.key)} className="flex w-full items-center gap-3 rounded-xl bg-[var(--paper)] p-3 text-left"><span className="grid size-9 place-items-center rounded-xl bg-[var(--forest-soft)] text-[var(--forest)]"><CalendarClock aria-hidden="true" className="size-4" /></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{displayName(pattern)}</strong><span className="mt-1 block text-xs capitalize text-[var(--muted)]">{pattern.categoryName || "Uncategorized"} · {pattern.frequency} · {pattern.status}</span></span><span className="text-right"><strong className="block font-mono text-sm">{money(pattern.latestAmount, pattern.currency)}</strong><span className="text-[10px] text-[var(--muted)]">{pattern.transactionIds.length} payments</span></span></button>)}{!analysis.patterns.length ? <Empty text="No repeated payment pattern has enough evidence yet." /> : null}</div></article>
      <article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Subscriptions by month</h2><p className="mt-1 text-sm text-[var(--muted)]">Actual payments and budgeting equivalents stay separate.</p><div className="mt-4 space-y-3">{subscriptions.map((pattern) => <button key={pattern.key} onClick={() => setSelectedKey(pattern.key)} className="block w-full rounded-xl border border-[var(--line)] p-3 text-left"><span className="flex items-center justify-between gap-3"><strong className="truncate text-sm">{displayName(pattern)}</strong><span className="rounded-full bg-[var(--paper)] px-2 py-1 text-[10px] capitalize">{pattern.frequency} · {pattern.status}</span></span><span className="mt-2 grid grid-cols-2 gap-2 text-xs"><span>Actual last payment<strong className="mt-1 block font-mono">{money(pattern.latestAmount, pattern.currency)}</strong></span><span>Monthly budget equivalent<strong className="mt-1 block font-mono">{money(pattern.frequency === "annual" ? pattern.latestAmount / 12 : pattern.latestAmount, pattern.currency)}</strong></span></span><span className="mt-2 flex flex-wrap gap-1">{subscriptionMonths(pattern, workspace).map((month) => <span key={month.month} className="rounded-md bg-[var(--paper)] px-2 py-1 text-[10px]"><strong>{month.month}</strong> · {money(month.amount, month.currency)}</span>)}</span><span className="mt-2 block text-[10px] text-[var(--muted)]">Last {pattern.lastPayment} · expected {pattern.expectedNextPayment || "uncertain"}</span></button>)}
        <div className="rounded-xl border border-dashed border-[var(--line)] p-3"><span className="flex items-center justify-between gap-3"><strong className="text-sm">Adobe</strong><span className="rounded-full bg-[var(--paper)] px-2 py-1 text-[10px]">needs evidence</span></span><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Known subscription, but no Adobe transaction exists in the imported statements. No amount is added until a payment is found.</p></div>
        <div className="rounded-xl border border-dashed border-[var(--line)] p-3"><span className="flex items-center justify-between gap-3"><strong className="text-sm">SWEAT Train (via Apple)</strong><span className="rounded-full bg-[#f7e3df] px-2 py-1 text-[10px] text-[var(--danger)]">inactive</span></span><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Cancelled subscription. The imported data has isolated Apple charges of USD 9.99 and USD 12.99; neither is assigned to SWEAT until you confirm which one it was.</p>{sweatCandidates.length ? <button onClick={() => openTransactions({ title: "Possible SWEAT Train Apple charges", transactionIds: sweatCandidates.map((transaction) => transaction.id), range: sweatRange })} className="mt-2 text-xs font-semibold text-[var(--forest)] underline underline-offset-4">Open {sweatCandidates.length} candidate transactions</button> : null}</div>
      </div></article></div>
  </section>;
}

function RecurringDetail({ pattern, obligationId, workspace, mutate, openTransactions, onBack }: { pattern: RecurringPattern; obligationId: string | null; workspace: WorkspaceData; mutate: FinanceMutate; openTransactions: OpenTransactions; onBack: () => void }) {
  const rows = workspace.transactions.filter((transaction) => pattern.transactionIds.includes(transaction.id)).sort((left, right) => left.occurred_at.localeCompare(right.occurred_at));
  const months = monthlyRows(rows);
  const max = Math.max(1, ...months.map((month) => month.usd ?? 0));
  const [editing, setEditing] = useState(false);
  const transactionRange = { from: rows[0]?.occurred_at.slice(0, 10) ?? `${workspace.asOfDate.slice(0, 4)}-01-01`, to: rows.at(-1)?.occurred_at.slice(0, 10) ?? workspace.asOfDate };
  return <section className="mt-7 space-y-5"><button onClick={onBack} className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--forest)]"><ChevronLeft aria-hidden="true" className="size-4" />All recurring expenses</button><div className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--muted)]">Recurring-expense detail</p><h2 className="mt-2 text-2xl font-semibold">{displayName(pattern)}</h2><p className="mt-1 text-sm capitalize text-[var(--muted)]">{pattern.categoryName || "Uncategorized"} · {pattern.frequency} · {pattern.status}</p></div><div className="flex gap-2"><button onClick={() => openTransactions({ title: `${displayName(pattern)} transactions`, transactionIds: pattern.transactionIds, range: transactionRange })} className="rounded-xl border border-[var(--line)] px-3 py-2 text-sm font-semibold">Open {pattern.transactionIds.length} transactions</button>{obligationId ? <button onClick={() => setEditing((value) => !value)} className="rounded-xl bg-[var(--forest)] px-3 py-2 text-sm font-semibold text-white">Edit rule</button> : null}</div></div>{editing && obligationId ? <RuleEditor pattern={pattern} obligationId={obligationId} workspace={workspace} mutate={mutate} /> : null}
      <div className="mt-6 grid gap-3 sm:grid-cols-4"><DetailMetric label="Latest monthly cost" value={money(pattern.latestAmount, pattern.currency)} /><DetailMetric label="Typical payment" value={money(pattern.medianAmount, pattern.currency)} /><DetailMetric label="Missing months" value={String(pattern.missingMonths.length)} /><DetailMetric label="Possible double payments" value={String(pattern.doubledTransactionIds.length)} /></div>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1fr_360px]"><article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Price evolution</h2><p className="mt-1 text-sm text-[var(--muted)]">Original amount and historical USD value at each payment date</p><div className="mt-5 space-y-3">{months.map((month) => <button key={month.month} onClick={() => openTransactions({ title: `${displayName(pattern)} · ${month.month}`, transactionIds: month.transactionIds, range: transactionRange })} className="grid w-full grid-cols-[70px_1fr_auto] items-center gap-3 text-left"><span className="text-xs">{month.month}</span><span className="h-2 overflow-hidden rounded-full bg-[var(--paper-deep)]"><span className="block h-full rounded-full bg-[var(--forest)]" style={{ width: `${Math.max(3, (month.usd ?? 0) / max * 100)}%` }} /></span><span className="text-right"><strong className="block font-mono text-xs">{month.usd == null ? "USD rate needed" : money(month.usd, "USD")}</strong><span className="text-[10px] text-[var(--muted)]">{money(month.original, month.currency)}</span></span></button>)}</div></article><article className="rounded-[22px] border border-[var(--line)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Cash flow vs covered month</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">A July payment can remain entirely in July cash flow while allocations assign part of the cost to June.</p>{obligationId ? <AllocationForm obligationId={obligationId} rows={rows} workspace={workspace} mutate={mutate} /> : <p className="mt-4 rounded-xl bg-[var(--paper)] p-3 text-xs text-[var(--muted)]">Refresh analysis to save this recurring pattern before allocating service months.</p>}</article></div>
    <div className="overflow-x-auto rounded-[20px] border border-[var(--line)] bg-[var(--surface)]"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[var(--paper)] text-xs uppercase tracking-[0.08em] text-[var(--muted)]"><tr><th className="px-4 py-3">Payment date</th><th className="px-4 py-3">Cash amount</th><th className="px-4 py-3">USD at payment</th><th className="px-4 py-3">Exchange-rate source</th><th className="px-4 py-3">Covered month</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3">{row.occurred_at.slice(0, 10)}</td><td className="px-4 py-3 font-mono">{money(Math.abs(Number(row.original_amount ?? row.amount)), row.original_currency ?? row.currency)}</td><td className="px-4 py-3 font-mono">{usd(row) == null ? "Rate needed" : money(usd(row)!, "USD")}</td><td className="px-4 py-3 text-xs text-[var(--muted)]">{row.currency === "USD" ? "USD account amount" : row.reporting_value ? `${row.reporting_value.source} · ${row.reporting_value.rate_to_reporting}` : "Not configured"}</td><td className="px-4 py-3 text-xs">{row.expense_allocations?.length ? row.expense_allocations.map((allocation) => `${allocation.service_month.slice(0, 7)}${allocation.is_estimated ? " (estimated)" : ""}`).join(", ") : row.occurred_at.slice(0, 7)}</td></tr>)}</tbody></table></div>
  </section>;
}

function RuleEditor({ pattern, obligationId, workspace, mutate }: { pattern: RecurringPattern; obligationId: string; workspace: WorkspaceData; mutate: FinanceMutate }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await mutate(`/api/recurring/${obligationId}`, "PATCH", { providerName: data.get("providerName"), categoryId: data.get("categoryId") || null, frequency: data.get("frequency"), status: data.get("status"), countryCode: data.get("countryCode") || null }); }; return <form onSubmit={(event) => void submit(event)} className="mt-5 grid gap-3 rounded-xl bg-[var(--paper)] p-4 sm:grid-cols-5"><Field label="Provider"><input name="providerName" defaultValue={displayName(pattern)} className="field" /></Field><Field label="Category"><select name="categoryId" className="field"><option value="">Uncategorized</option>{workspace.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Frequency"><select name="frequency" defaultValue={pattern.frequency} className="field"><option>weekly</option><option>monthly</option><option>quarterly</option><option>annual</option><option>uncertain</option></select></Field><Field label="Status"><select name="status" defaultValue={pattern.status} className="field"><option>active</option><option>inactive</option><option>uncertain</option></select></Field><Field label="Country"><input name="countryCode" className="field" placeholder="AR" /></Field><button className="h-10 self-end rounded-xl bg-[var(--forest)] px-4 text-sm font-semibold text-white">Save rule</button></form>; }
function AllocationForm({ obligationId, rows, workspace, mutate }: { obligationId: string; rows: WorkspaceTransaction[]; workspace: WorkspaceData; mutate: FinanceMutate }) { const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const allocations = [1,2].flatMap((index) => { const month = String(data.get(`month${index}`) || ""); const amount = Number(data.get(`amount${index}`) || 0); return month && amount > 0 ? [{ serviceMonth: month, amount, currency: String(data.get("currency") || "USD"), reportingAmount: null, estimated: data.get("estimated") === "on" }] : []; }); await mutate(`/api/recurring/${obligationId}/allocations`, "PUT", { transactionId: data.get("transactionId"), allocations }); }; return <form onSubmit={(event) => void submit(event)} className="mt-4 space-y-3"><Field label="Payment"><select name="transactionId" className="field">{rows.map((row) => <option key={row.id} value={row.id}>{row.occurred_at.slice(0,10)} · {money(Math.abs(Number(row.amount)), row.currency)}</option>)}</select></Field><div className="grid grid-cols-2 gap-2"><Field label="Covered month 1"><input name="month1" type="month" required className="field" /></Field><Field label="Amount 1"><input name="amount1" type="number" step="any" required className="field" /></Field><Field label="Covered month 2"><input name="month2" type="month" className="field" /></Field><Field label="Amount 2"><input name="amount2" type="number" step="any" className="field" /></Field></div><Field label="Original currency"><input name="currency" defaultValue={rows[0]?.currency ?? "USD"} className="field" /></Field><label className="flex items-center gap-2 text-xs"><input name="estimated" type="checkbox" /> Mark the split as estimated</label><button disabled={workspace.mode !== "live"} className="w-full rounded-xl bg-[var(--forest)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-45">Save covered months</button></form>; }
function monthlyRows(rows: WorkspaceTransaction[]) { const map = new Map<string, { month: string; original: number; currency: string; usd: number | null; transactionIds: string[] }>(); for (const row of rows) { const month = row.occurred_at.slice(0,7); const current = map.get(month) ?? { month, original: 0, currency: row.original_currency ?? row.currency, usd: 0, transactionIds: [] }; current.original += Math.abs(Number(row.original_amount ?? row.amount)); const value = usd(row); current.usd = value == null || current.usd == null ? null : current.usd + value; current.transactionIds.push(row.id); map.set(month,current); } return [...map.values()].sort((a,b)=>a.month.localeCompare(b.month)); }
function usd(row: WorkspaceTransaction) { return row.currency === "USD" ? Math.abs(Number(row.amount)) : row.reporting_value ? Math.abs(Number(row.reporting_value.reporting_amount)) : null; }
function displayName(pattern: RecurringPattern) { return /hospital\s*alem[aá]n|hospitalaleman/i.test(`${pattern.key} ${pattern.providerName}`) ? "Hospital Alemán" : pattern.providerName; }
function money(value: number, currency: string) { try { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); } catch { return `${currency} ${value.toLocaleString()}`; } }
function DetailMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[var(--paper)] p-3"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-semibold text-[var(--muted)]">{label}{children}</label>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-[var(--paper)] p-4 text-sm text-[var(--muted)]">{text}</p>; }
function messageOf(error: unknown) { return error instanceof Error ? error.message : "The analysis could not be refreshed."; }
function evidenceRange(rows: WorkspaceTransaction[], today: string) { const dates = rows.map((row) => row.occurred_at.slice(0, 10)).sort(); return { from: dates[0] ?? `${today.slice(0, 4)}-01-01`, to: dates.at(-1) ?? today }; }
function subscriptionMonths(pattern: RecurringPattern, workspace: WorkspaceData) { const rows = workspace.transactions.filter((row) => pattern.transactionIds.includes(row.id)); const monthly = new Map<string, { month: string; amount: number; currency: string }>(); for (const row of rows) { const month = row.occurred_at.slice(0, 7); const current = monthly.get(month) ?? { month, amount: 0, currency: row.currency }; current.amount += Math.abs(Number(row.amount)); monthly.set(month, current); } return [...monthly.values()].sort((left, right) => right.month.localeCompare(left.month)).slice(0, 6); }
